name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20, 18, 16]
    name: Run tests on Node.js ${{ matrix.node-version }}
    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage --coverageReporters=cobertura
        env:
          CI: true

      - name: Upload coverage report
        if: ${{ matrix.node-version == '20' }}
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/cobertura-coverage.xml
          flags: unittests
          name: codecov
